---
abstract: 'tcp redirections server'
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: rinetd.pl
no_index:
  directory:
    - t
    - inc
requires:
  Daemon::Generic: 0
  File::Flock: 0
  File::Slurp: 0
  IO::Event: 0.809
  Net::Netmask: 0
  Pod::Usage: 0
resources:
  repository: http://github.com/muir/rinetd.pl
version: 1.21
